-- Estratégia passa a ter duas frentes: chão e internet.
-- 'strategy' continua válido para os itens antigos, exibidos como "Geral".
alter table public.checklist_items drop constraint if exists checklist_items_category_check;
alter table public.checklist_items add constraint checklist_items_category_check
  check (category in ('document','electoral_requirement','strategy','ground','digital'));

-- Projeção de votos por região, para o gráfico de pizza do estado.
create table if not exists public.vote_projections (
  id bigint generated by default as identity primary key,
  candidate_id bigint not null references public.candidates(id) on delete cascade,
  region text not null,
  projected_votes integer not null check (projected_votes >= 0),
  created_at timestamptz not null default now(),
  unique (candidate_id, region)
);

comment on table public.vote_projections is 'Projeção de votos por região do estado, por candidato. Alimenta o gráfico da tela de Estratégia.';

alter table public.vote_projections enable row level security;

create policy "agency members vote projections" on public.vote_projections
  for all to authenticated
  using (exists (select 1 from public.agency_members m where m.auth_user_id = (select auth.uid())))
  with check (exists (select 1 from public.agency_members m where m.auth_user_id = (select auth.uid())));
